### PR TITLE
Add Cinestill 400D and CatLABS X FILM 80

### PR DESCRIPTION
**Pull request by krispayne**

### CODE REVIEW

**Comment by krispayne** [comment]
Any chance of this getting merged?

**Comment by gmoigneu** [comment]
Thank you so much Kris! I'm deeply sorry it took so long!

**Comment by gmoigneu** [comment]
I'm publishing the new version in a few minutes (1.4)

**Comment by krispayne** [comment]
All good. Thanks!
Any future plans for the app?

**Comment by gmoigneu** [comment]
I'm not sure. I've put it aside for a few months and just started working back on it again. 

I need to check some of the formulas. Portra seems incorrect.

Let me know if you have any ideas.

**Comment by krispayne** [comment]
No ideas, just curious 😊

**Pull request merged**
